INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'johndoe@example.com', 'p@ssword123', 'user', 'Johnny');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'janedoe@example.com', 'securePass!45', 'user', 'Janie');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'sammy_rose@example.com', 'sammyPass!678', 'user', 'Sammy');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'mike_jones@example.com', 'jonesy12$%56', 'user', 'Mikey');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'lucy.potter@example.com', 'lucy789!potter', 'user', 'LucyP');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'chris.murphy@example.com', 'Murphy2020!!', 'user', 'ChrisM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'mia.wang@example.com', 'Mia@12345', 'user', 'Mia');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'alex.smith@example.com', 'alexpass123!', 'user', 'AlexS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'olivia.brown@example.com', 'Olivia!brown78', 'user', 'Livy');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'charlie.davis@example.com', 'Charli#989', 'user', 'CharlieD');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'benjamin.white@example.com', 'Benny*56&!white', 'user', 'Benji');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'elizabeth.johnson@example.com', 'eliz@2020', 'user', 'LizzyJ');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'george.harris@example.com', 'Harris!pass123', 'user', 'Geo');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'emma.martin@example.com', 'emmapass321@', 'user', 'Emmy');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'harry.clark@example.com', 'harryP2*23', 'user', 'Hazz');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'sophia.lee@example.com', 'Sophia1@leo', 'user', 'SophieL');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'liam.garcia@example.com', 'LiamG_123', 'user', 'LiamG');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'isabella.martinez@example.com', 'Isabella123!', 'user', 'Izzy');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'noah.martin@example.com', 'Noah-999', 'user', 'NoahM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'james.morris@example.com', 'JamesM@99', 'user', 'Jimmy');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'charlotte.baker@example.com', 'Ch@rlie#67', 'user', 'CharlieB');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'william.evans@example.com', 'Will@w456', 'user', 'WillEvans');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'ava.jackson@example.com', 'Ava_456!jack', 'user', 'AvaJ');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'oliver.garcia@example.com', 'OliverG_2021', 'user', 'Olly');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'mia.miller@example.com', 'MiaMill123!', 'user', 'MiaM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'ethan.moore@example.com', 'Ethan!moore567', 'user', 'EthanM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'lucas.taylor@example.com', 'lucasT!987', 'user', 'LucasT');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'scarlett.james@example.com', 'Scarlet123@', 'user', 'Scar');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'henry.wilson@example.com', 'H@ry123#45', 'user', 'HarryW');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'grace.anderson@example.com', 'gr@ce789!an', 'user', 'GracieA');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'jackson.taylor@example.com', 'J@ckT!2020', 'user', 'JackT');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'lily.lee@example.com', 'Lily789!lee', 'user', 'Lil');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'david.miller@example.com', 'David!2023', 'user', 'DaveM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'ella.wilson@example.com', 'Ell@789!wil', 'user', 'Ellie');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'jack.harris@example.com', 'Jack!H@rris', 'user', 'JHarris');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'grace.moore@example.com', 'Grace!moore123', 'user', 'GracieM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'samuel.brown@example.com', 'S@muel123', 'user', 'SamB');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'zachary.davis@example.com', 'Zach@davis987', 'user', 'ZackD');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'madeline.martin@example.com', 'Madeline#1', 'user', 'Maddie');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'ryan.johnson@example.com', 'R@yan12345', 'user', 'Rye');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'elijah.smith@example.com', 'Elijah@567', 'user', 'Eli');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'luna.baker@example.com', 'LunaBaker#89', 'user', 'LunaB');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'andrew.lee@example.com', 'Andr3w!Lee', 'user', 'AndyL');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'zoe.martinez@example.com', 'Zoe2020!!', 'user', 'ZoeM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'akira.yamamoto@example.com', 'AkiYam123!', 'user', 'AkiraY');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'fatima.al-farsi@example.com', 'FatAl-123!', 'user', 'FatimaA');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'carlos.mendez@example.com', 'CarMen123!', 'user', 'CarlosM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'aisha.khan@example.com', 'AisKha123!', 'user', 'AishaK');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'luca.rossi@example.com', 'LucRos123!', 'user', 'LucaR');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'mei.chen@example.com', 'MeiChe123!', 'user', 'MeiC');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'ivan.petrov@example.com', 'IvaPet123!', 'user', 'IvanP');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'sara.johansson@example.com', 'SarJoh123!', 'user', 'SaraJ');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'mohammed.hassan@example.com', 'MohHas123!', 'user', 'MohammedH');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'pierre.dubois@example.com', 'PieDub123!', 'user', 'PierreD');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'anika.schmidt@example.com', 'AniSch123!', 'user', 'AnikaS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'raj.patel@example.com', 'RajPat123!', 'user', 'RajP');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'nina.popova@example.com', 'NinPop123!', 'user', 'NinaP');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'diego.fernandez@example.com', 'DieFer123!', 'user', 'DiegoF');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'leila.haddad@example.com', 'LeiHad123!', 'user', 'LeilaH');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'tomáš.novák@example.com', 'TomNov123!', 'user', 'TomášN');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'sofia.silva@example.com', 'SofSil123!', 'user', 'SofiaS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'ali.reza@example.com', 'AliRez123!', 'user', 'AliR');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'hiroshi.tanaka@example.com', 'HirTan123!', 'user', 'HiroshiT');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'isabella.ricci@example.com', 'IsaRic123!', 'user', 'IsabellaR');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'mateo.gomez@example.com', 'MatGom123!', 'user', 'MateoG');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'yara.nasr@example.com', 'YarNas123!', 'user', 'YaraN');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'jin.park@example.com', 'JinPar123!', 'user', 'JinP');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'elena.ivanova@example.com', 'EleIva123!', 'user', 'ElenaI');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'andres.lopez@example.com', 'AndLop123!', 'user', 'AndresL');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'amira.mohamed@example.com', 'AmiMoh123!', 'user', 'AmiraM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'tariq.rahman@example.com', 'TarRah123!', 'user', 'TariqR');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'lucia.martinez@example.com', 'LucMar123!', 'user', 'LuciaM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'kaito.sato@example.com', 'KaiSat123!', 'user', 'KaitoS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'zara.ahmed@example.com', 'ZarAhm123!', 'user', 'ZaraA');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'miguel.torres@example.com', 'MigTor123!', 'user', 'MiguelT');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'anna.kowalska@example.com', 'AnnKow123!', 'user', 'AnnaK');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'omar.suleiman@example.com', 'OmaSul123!', 'user', 'OmarS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'camila.rodriguez@example.com', 'CamRod123!', 'user', 'CamilaR');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'yuki.nakamura@example.com', 'YukNak123!', 'user', 'YukiN');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'hassan.ali@example.com', 'HasAli123!', 'user', 'HassanA');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'maria.gonzalez@example.com', 'MarGon123!', 'user', 'MariaG');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'stefan.ionescu@example.com', 'SteIon123!', 'user', 'StefanI');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'layla.hussein@example.com', 'LayHus123!', 'user', 'LaylaH');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'thiago.costa@example.com', 'ThiCos123!', 'user', 'ThiagoC');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'nadia.bashir@example.com', 'NadBas123!', 'user', 'NadiaB');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'kenji.fujimoto@example.com', 'KenFuj123!', 'user', 'KenjiF');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'rania.salem@example.com', 'RanSal123!', 'user', 'RaniaS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'pavel.morozov@example.com', 'PavMor123!', 'user', 'PavelM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'fernanda.lima@example.com', 'FerLim123!', 'user', 'FernandaL');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'ahmed.zaki@example.com', 'AhmZak123!', 'user', 'AhmedZ');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'svetlana.orlova@example.com', 'SveOrl123!', 'user', 'SvetlanaO');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'joão.pereira@example.com', 'JoãPer123!', 'user', 'JoãoP');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'mina.farouk@example.com', 'MinFar123!', 'user', 'MinaF');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'anton.volkov@example.com', 'AntVol123!', 'user', 'AntonV');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'aya.takahashi@example.com', 'AyaTak123!', 'user', 'AyaT');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'hugo.martins@example.com', 'HugMar123!', 'user', 'HugoM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'reem.khalil@example.com', 'ReeKha123!', 'user', 'ReemK');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'dmitry.sokolov@example.com', 'DmiSok123!', 'user', 'DmitryS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'noor.abdullah@example.com', 'NooAbd123!', 'user', 'NoorA');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'leonardo.barros@example.com', 'LeoBar123!', 'user', 'LeonardoB');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'tania.ramirez@example.com', 'TanRam123!', 'user', 'TaniaR');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'youssef.naguib@example.com', 'YouNag123!', 'user', 'YoussefN');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'beatriz.alves@example.com', 'BeaAlv123!', 'user', 'BeatrizA');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'khalid.mahmoud@example.com', 'KhaMah123!', 'user', 'KhalidM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'irina.smirnova@example.com', 'IriSmi123!', 'user', 'IrinaS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'pedro.almeida@example.com', 'PedAlm123!', 'user', 'PedroA');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'salma.youssef@example.com', 'SalYou123!', 'user', 'SalmaY');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'nikolai.ivanov@example.com', 'NikIva123!', 'user', 'NikolaiI');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'rui.oliveira@example.com', 'RuiOli123!', 'user', 'RuiO');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'farah.saad@example.com', 'FarSaa123!', 'user', 'FarahS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'andrei.popescu@example.com', 'AndPop123!', 'user', 'AndreiP');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'laila.zein@example.com', 'LaiZei123!', 'user', 'LailaZ');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'bruno.ferreira@example.com', 'BruFer123!', 'user', 'BrunoF');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'zeinab.hassan@example.com', 'ZeiHas123!', 'user', 'ZeinabH');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'igor.kuznetsov@example.com', 'IgoKuz123!', 'user', 'IgorK');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'mariana.souza@example.com', 'MarSou123!', 'user', 'MarianaS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'mustafa.ismail@example.com', 'MusIsm123!', 'user', 'MustafaI');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'tatiana.petrova@example.com', 'TatPet123!', 'user', 'TatianaP');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'ricardo.neves@example.com', 'RicNev123!', 'user', 'RicardoN');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'hala.sharif@example.com', 'HalSha123!', 'user', 'HalaS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'viktor.lebedev@example.com', 'VikLeb123!', 'user', 'ViktorL');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'ines.monteiro@example.com', 'IneMon123!', 'user', 'InesM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'aliya.kamal@example.com', 'AliKam123!', 'user', 'AliyaK');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'gustavo.ribeiro@example.com', 'GusRib123!', 'user', 'GustavoR');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'samira.nasser@example.com', 'SamNas123!', 'user', 'SamiraN');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'evgeny.kozlov@example.com', 'EvgKoz123!', 'user', 'EvgenyK');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'carla.vieira@example.com', 'CarVie123!', 'user', 'CarlaV');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'bilal.fahmy@example.com', 'BilFah123!', 'user', 'BilalF');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'natalia.romanova@example.com', 'NatRom123!', 'user', 'NataliaR');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('eduardo.teixeira@example.com', 'EduTei123!', 'user', 'EduardoT');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ( 'amina.said@example.com', 'AmiSai123!', 'user', 'AminaS');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('sergey.antonov@example.com', 'SerAnt123!', 'user', 'SergeyA');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('daniela.moura@example.com', 'DanMou123!', 'user', 'DanielaM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('oksana.fedorova@example.com', 'OksFed123!', 'user', 'OksanaF');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('mohamed.abbas@example.com', 'MohAbb123!', 'user', 'MohamedA');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('renata.castro@example.com', 'RenCas123!', 'user', 'RenataC');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('yasin.bakr@example.com', 'YasBak123!', 'user', 'YasinB');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('larissa.mendes@example.com', 'LarMen123!', 'user', 'LarissaM');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('zainab.ali@example.com', 'ZaiAli123!', 'user', 'ZainabA');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('rodrigo.pinto@example.com', 'RodPin123!', 'user', 'RodrigoP');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('fatma.yildiz@example.com', 'FatYil123!', 'user', 'FatmaY');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('leonor.correia@example.com', 'LeoCor123!', 'user', 'LeonorC');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('mahmoud.tarek@example.com', 'MahTar123!', 'user', 'MahmoudT');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('isabel.fonseca@example.com', 'IsaFon123!', 'user', 'IsabelF');
INSERT INTO USUARIO (email, contraseña, rol, nombre_usuario) VALUES ('hamza.nasser@example.com', 'HamNas123!', 'user', 'HamzaN');