export type Opcion = { label: string; value: string };

export const DEPORTES: Opcion[] = [
    { label: 'Ajedrez', value: 'Ajedrez' },
    { label: 'Artes Marciales', value: 'Artes Marciales' },
    { label: 'Atletismo', value: 'Atletismo' },
    { label: 'Badminton', value: 'Badminton' },
    { label: 'Balonmano', value: 'Balonmano' },
    { label: 'Basquet', value: 'Basquet' },
    { label: 'Béisbol', value: 'Béisbol' },
    { label: 'Billar', value: 'Billar' },
    { label: 'Boxeo', value: 'Boxeo' },
    { label: 'Ciclismo', value: 'Ciclismo' },
    { label: 'Críquet', value: 'Críquet' },
    { label: 'Crossfit', value: 'Crossfit' },
    { label: 'Danza Deportiva', value: 'Danza Deportiva' },
    { label: 'Entrenamiento de fuerza', value: 'Entrenamiento de fuerza' },
    { label: 'Equitación', value: 'Equitación' },
    { label: 'Escalada', value: 'Escalada' },
    { label: 'Esgrima', value: 'Esgrima' },
    { label: 'Esquí', value: 'Esquí' },
    { label: 'Frisbee', value: 'Frisbee' },
    { label: 'Futbol', value: 'Futbol' },
    { label: 'Fútbol Americano', value: 'Fútbol Americano' },
    { label: 'Gimnasia', value: 'Gimnasia' },
    { label: 'Golf', value: 'Golf' },
    { label: 'Hockey', value: 'Hockey' },
    { label: 'Lucha Libre', value: 'Lucha Libre' },
    { label: 'Motocross', value: 'Motocross' },
    { label: 'Natación', value: 'Natación' },
    { label: 'Padel', value: 'Padel' },
    { label: 'Parkour', value: 'Parkour' },
    { label: 'Patinaje', value: 'Patinaje' },
    { label: 'Petanca', value: 'Petanca' },
    { label: 'Ping Pong', value: 'Ping Pong' },
    { label: 'Piragüismo', value: 'Piragüismo' },
    { label: 'Remo', value: 'Remo' },
    { label: 'Rugby', value: 'Rugby' },
    { label: 'Running', value: 'Running' },
    { label: 'Senderismo', value: 'Senderismo' },
    { label: 'Skateboarding', value: 'Skateboarding' },
    { label: 'Snowboard', value: 'Snowboard' },
    { label: 'Squash', value: 'Squash' },
    { label: 'Surf', value: 'Surf' },
    { label: 'Tenis', value: 'Tenis' },
    { label: 'Tiro con Arco', value: 'Tiro con Arco' },
    { label: 'Triatlón', value: 'Triatlón' },
    { label: 'Voleibol', value: 'Voleibol' },
    { label: 'Waterpolo', value: 'Waterpolo' },
].sort((a, b) => a.label.localeCompare(b.label, 'es', { sensitivity: 'base' }));